import argparse
import os
import transaction
import bcrypt
from pyramid.paster import get_appsettings, setup_logging
from sqlalchemy import engine_from_config
from ..models import get_tm_session, get_session_factory
from ..models.recipe import Recipe
from ..models.user import User
from ..models.comment import Comment

def main(argv=None):
    parser = argparse.ArgumentParser(description="Seed the database with initial data.")
    parser.add_argument(
        "config_uri",
        nargs="?",
        default=os.environ.get("APP_CONFIG", "development.ini"),
        help="Path to the Pyramid config file (default: APP_CONFIG or development.ini)",
    )
    args = parser.parse_args(argv)
    config_uri = args.config_uri
    setup_logging(config_uri)
    settings = get_appsettings(config_uri)

    env_db_url = os.getenv("DATABASE_URL")
    if env_db_url:
        settings["sqlalchemy.url"] = env_db_url

    engine = engine_from_config(settings, 'sqlalchemy.')

    session_factory = get_session_factory(engine)

    with transaction.manager:
        dbsession = get_tm_session(session_factory, transaction.manager)

        # Tambahkan user biasa
        existing_user = dbsession.query(User).filter_by(email='budi@example.com').first()
        if not existing_user:
            user1 = User(
                username='budi',
                email='budi@example.com',
                password=bcrypt.hashpw('budi1234'.encode('utf-8'), bcrypt.gensalt()).decode('utf-8'),
                role='user'
            )
            dbsession.add(user1)
        else:
            user1 = existing_user

        # Tambahkan admin
        existing_admin = dbsession.query(User).filter_by(email='admin@example.com').first()
        if not existing_admin:
            admin = User(
                username='admin',
                email='admin@example.com',
                password=bcrypt.hashpw('admin1234'.encode('utf-8'), bcrypt.gensalt()).decode('utf-8'),
                role='admin'
            )
            dbsession.add(admin)

        dbsession.flush()

        recipes_data = [
            {
                "title": "Rendang",
                "description": "Rendang daging sapi khas Minangkabau yang dimasak perlahan hingga bumbu pekat, berminyak, dan meresap sampai ke serat daging.",
                "ingredients": "1 kg daging sapi bagian paha/sengkel, potong kotak besar 5–6 cm (jangan terlalu kecil supaya tidak hancur saat dimasak lama)\n1,2 liter santan kental (dari 2 butir kelapa tua) + 400 ml santan encer (opsional untuk awal perebusan)\n150 gram bawang merah, kupas\n60 gram bawang putih, kupas\n120 gram cabai merah keriting (sesuaikan pedas)\n10 gram cabai rawit merah (opsional, jika ingin lebih pedas)\n40 gram jahe\n60 gram lengkuas, memarkan\n3 batang serai, memarkan\n5 lembar daun jeruk, buang tulangnya\n2 lembar daun kunyit, ikat simpul\n1 batang kayu manis 5 cm (opsional)\n3 butir cengkeh (opsional)\n3 butir kapulaga (opsional)\n2 sendok makan ketumbar sangrai\n1 sendok teh jintan sangrai (opsional)\n1/2 sendok teh pala bubuk (opsional)\n2 sendok teh garam (sesuaikan)\n1,5 sendok makan gula merah, sisir halus (opsional penyeimbang)\n2 sendok makan minyak untuk menumis (opsional, jika santan tidak cukup berminyak di awal)\nAir panas secukupnya (hanya jika perlu saat kuah terlalu cepat susut)",
                "steps": "Siapkan daging: cuci cepat di air mengalir, tiriskan, lalu lap dengan tisu dapur agar permukaan kering; langkah ini membantu daging tidak berair saat masuk santan\nHaluskan bumbu: blender bawang merah, bawang putih, cabai, jahe, ketumbar, jintan dengan sedikit santan encer atau air hingga benar-benar halus tanpa tekstur kasar; bumbu yang halus membuat rendang lebih legit dan tidak “berpasir”\nPanaskan wajan besar atau panci dasar tebal: gunakan api sedang; bila menggunakan minyak, tuang tipis saja, lalu tumis bumbu halus hingga harum dan matang, aduk terus sampai warna bumbu sedikit menggelap dan minyak mulai keluar (tanda bumbu matang)\nMasukkan aromatik: masukkan serai, daun jeruk, daun kunyit, lengkuas, serta rempah opsional (kayu manis, cengkeh, kapulaga); aduk 1–2 menit agar aromanya keluar\nTuang santan: masukkan santan kental (dan santan encer bila dipakai) sambil terus diaduk; pertahankan api sedang-kecil; kunci rendang adalah aduk rutin agar santan tidak pecah dan tidak gosong di dasar\nMasukkan daging: ketika santan mulai panas dan bumbu tercampur rata, masukkan potongan daging; aduk perlahan agar seluruh permukaan daging terlapisi bumbu\nMasak fase “kalio”: biarkan mendidih kecil (bukan mendidih besar) selama 60–90 menit; aduk setiap 3–5 menit, terutama setelah santan mulai menyusut; pada fase ini daging mulai empuk dan kuah mengental\nBumbui: masukkan garam dan gula merah; cicipi—rasa harus gurih, pedas, dan sedikit manis seimbang; koreksi garam bertahap agar tidak keasinan saat kuah makin susut\nMasak fase “pengeringan”: setelah kuah semakin pekat dan mulai berminyak, kecilkan api; aduk lebih sering (1–2 menit sekali) karena risiko gosong meningkat; pastikan mengeruk dasar panci saat mengaduk\nTentukan tingkat kering: untuk rendang hitam kering, lanjutkan memasak sampai bumbu menempel pada daging, kuah benar-benar habis, dan warna berubah cokelat tua; biasanya total 3–4 jam tergantung api dan lebar panci\nIstirahatkan: matikan api, diamkan 15–20 menit agar minyak naik dan bumbu “mengunci” di daging; sajikan hangat\nSimpan: rendang makin enak keesokan hari; simpan di wadah tertutup dalam kulkas 3–5 hari atau freezer 1–2 bulan; panaskan ulang dengan api kecil agar tidak kering berlebihan",
                "image": "https://img.freepik.com/free-photo/delicious-goulash-ready-dinner_23-2149370898.jpg?t=st=1766075648~exp=1766079248~hmac=6542b90cd95221c915b663253ab02e6a079060f46bf35683c7412c5da556fbdd&w=2000",
            },
            {
                "title": "Sate Padang",
                "description": "Sate daging sapi dengan kuah kental berempah khas Padang, gurih pedas, dan aromatik.",
                "ingredients": "600 gram daging sapi (campur daging + sedikit lemak untuk rasa), potong dadu 2–3 cm\n300 gram lidah sapi (opsional), rebus terpisah hingga empuk lalu potong dadu\n1,5 liter air untuk merebus\n2 batang serai, memarkan\n3 lembar daun jeruk\n2 lembar daun salam\n1 ruas lengkuas, memarkan\n2 sendok teh garam (sesuaikan)\n1 sendok teh gula pasir (opsional)\n2 sendok makan tepung beras (untuk pengental)\n3 sendok makan air (untuk melarutkan tepung)\n20 tusuk sate, rendam air 30 menit agar tidak cepat gosong\nBumbu halus kuah: 10 butir bawang merah\n4 siung bawang putih\n8 buah cabai merah keriting\n3 butir kemiri sangrai\n1 sendok teh kunyit bubuk atau 2 ruas kunyit segar\n1/2 sendok teh jintan sangrai\n1 sendok teh ketumbar sangrai\n1 ruas jahe\nPelengkap: bawang goreng secukupnya\nPelengkap: ketupat/lontong, potong\nPelengkap: kerupuk merah atau kerupuk jangek (opsional)\nMinyak 2 sendok makan untuk menumis bumbu",
                "steps": "Rebus daging: masukkan daging sapi ke panci, tuang 1,5 liter air; rebus hingga mendidih, buang buih/kotoran di permukaan agar kuah bersih; masukkan serai, daun jeruk, daun salam, lengkuas; kecilkan api dan rebus 60–90 menit sampai daging empuk\nAngkat daging: tiriskan daging, sisihkan; saring kaldu rebusan dan ukur kembali volumenya (target 1–1,2 liter; jika berlebih, rebus sebentar untuk mengurangi)\nSiapkan bumbu kuah: haluskan semua bumbu halus hingga lembut; tumis dengan minyak api sedang sampai harum, matang, dan tidak langu; bumbu harus matang agar kuah tidak getir\nMasukkan bumbu ke kaldu: tuang bumbu tumis ke dalam kaldu; didihkan kecil 10–15 menit agar bumbu menyatu; bumbui dengan garam dan gula; cicipi—harus gurih pedas dan wangi rempah\nKentalin kuah: larutkan tepung beras dengan 3 sdm air sampai licin tanpa gumpal; tuang perlahan ke kuah sambil diaduk terus; masak 5–8 menit sampai kuah mengental dan mengilap; jika terlalu kental tambahkan sedikit kaldu, jika kurang kental tambahkan sedikit larutan tepung lagi\nTusuk sate: tusuk potongan daging (dan lidah jika pakai) pada tusuk sate; padatkan tapi jangan terlalu rapat agar matang merata\nBakar sate: panaskan panggangan; bakar sate sambil dibolak-balik; oles tipis kuah atau sedikit minyak agar tidak kering; bakar sampai ada aroma smoky dan tepi daging sedikit karamel\nSajikan: tata lontong/ketupat di piring, letakkan sate, siram kuah panas kental, taburi bawang goreng; sajikan dengan kerupuk\nTips rasa: jika ingin kuah lebih “nendang”, tambahkan sedikit kaldu tulang atau sedikit bubuk kari/kaldu sapi (opsional) namun tetap dominan bumbu Padang",
                "image": "https://media.istockphoto.com/id/473455072/id/foto/bidang-02.jpg?s=1024x1024&w=is&k=20&c=kNRG1bgrzP7Sp3ZG0PyfJ5rC_CW-4kBfMCv80yPIA_I=",
            },
            {
                "title": "Soto Ayam Lamongan",
                "description": "Soto ayam kuning gurih dengan koya, segar, dan kaya aroma bumbu rempah.",
                "ingredients": "1 ekor ayam (900–1100 gram), potong 4–6 bagian\n2 liter air untuk merebus\n2 batang serai, memarkan\n3 lembar daun jeruk\n2 lembar daun salam\n1 ruas lengkuas, memarkan\n2 sendok makan minyak untuk menumis\nBumbu halus: 10 butir bawang merah\n4 siung bawang putih\n3 ruas kunyit, bakar sebentar\n2 ruas jahe\n1 sendok teh ketumbar sangrai\n3 butir kemiri sangrai\nGaram 2 sendok teh (sesuaikan)\nGula 1/2 sendok teh (opsional)\nMerica 1/2 sendok teh\nPelengkap: soun/bihun 150 gram, seduh air panas lalu tiriskan\nPelengkap: kol iris halus 150 gram\nPelengkap: tauge 150 gram, seduh 30 detik\nPelengkap: telur rebus 4 butir, belah dua\nPelengkap: jeruk nipis\nPelengkap: daun bawang iris\nPelengkap: seledri iris\nPelengkap: bawang goreng\nKoya: 6 siung bawang putih, goreng\nKoya: 150 gram kerupuk udang, hancurkan\nSambal: cabai rawit secukupnya + garam + sedikit kuah soto",
                "steps": "Rebus ayam: masukkan ayam ke panci dengan 2 liter air; didihkan lalu buang buih agar kuah jernih; masukkan serai, daun jeruk, daun salam, lengkuas; rebus api kecil 30–40 menit sampai ayam matang dan empuk\nAngkat ayam: tiriskan ayam; suwir daging saat sudah agak hangat; kulit dan tulang bisa dimasukkan kembali ke kuah untuk memperkaya kaldu 10–15 menit lalu angkat lagi\nSiapkan bumbu: haluskan bawang merah, bawang putih, kunyit, jahe, ketumbar, kemiri hingga lembut; tumis dengan 2 sdm minyak sampai harum dan benar-benar matang (warna bumbu lebih pekat dan tidak berair)\nSatukan kuah: masukkan bumbu tumis ke dalam kuah kaldu; aduk rata lalu didihkan kecil 10–15 menit agar bumbu “matang” di kuah; bumbui dengan garam, merica, dan sedikit gula; cicipi dan koreksi\nBuat koya: haluskan bawang putih goreng dan kerupuk udang sampai halus berpasir; simpan kering agar tidak melempem\nSiapkan pelengkap: seduh soun, seduh tauge, iris kol, rebus telur, siapkan sambal dan jeruk nipis\nPenyajian: di mangkuk, masukkan soun/kol/tauge, tambahkan suwiran ayam, siram kuah panas; taburi daun bawang, seledri, bawang goreng, dan koya; tambahkan perasan jeruk nipis sesuai selera\nKontrol rasa: soto enak jika gurihnya jelas tapi tidak asin, aromanya wangi kunyit dan serai, dan segarnya datang dari jeruk nipis + sambal",
                "image": "https://img.freepik.com/free-photo/close-up-high-protein-soup-meal_23-2149098849.jpg?t=st=1766075464~exp=1766079064~hmac=db959be93e26e10b92be37246ccfeeab34a41f27031ff6d72313265fb7c38e50&w=2000",
            },
            {
                "title": "Nasi Goreng Kampung",
                "description": "Nasi goreng sederhana dengan bumbu ulek, aroma smokey, dan rasa gurih pedas khas rumahan.",
                "ingredients": "2 piring nasi putih dingin (nasi sisa semalam lebih bagus, butiran tidak lembek)\n3 siung bawang putih\n6 butir bawang merah\n5 cabai rawit merah (sesuaikan)\n1 cabai merah besar (opsional untuk warna)\n1/2 sendok teh terasi bakar (opsional)\n2 sendok makan kecap manis\n1 sendok makan kecap asin (opsional)\n1 sendok teh garam (sesuaikan)\n1/2 sendok teh merica\n1 butir telur\n100 gram ayam suwir atau sosis/udang (opsional)\n1 batang daun bawang, iris\n2 sendok makan minyak goreng\nPelengkap: acar timun\nPelengkap: kerupuk\nPelengkap: irisan timun dan tomat",
                "steps": "Siapkan nasi: pastikan nasi benar-benar dingin dan terurai; jika menggumpal, remas pelan dengan tangan bersih atau garpu agar butiran terpisah\nHaluskan bumbu: ulek bawang merah, bawang putih, cabai, dan terasi sampai halus; bumbu ulek memberi rasa “kampung” lebih kuat dibanding blender\nPanaskan wajan: gunakan wajan besar dan api tinggi agar muncul aroma wok hei; tuang minyak dan panaskan sampai minyak sedikit beriak\nMasukkan bumbu: tumis bumbu halus sampai harum dan matang; aduk cepat agar tidak gosong; bumbu matang ditandai aromanya tidak menyengat mentah dan warnanya sedikit lebih gelap\nMasukkan telur: dorong bumbu ke pinggir wajan, pecahkan telur di tengah; orak-arik sampai setengah matang lalu campur dengan bumbu\nMasukkan isian: jika pakai ayam/udang/sosis, masukkan dan tumis hingga panas merata dan tidak berair\nMasukkan nasi: masukkan nasi sedikit demi sedikit sambil ditekan-tekan dengan spatula agar bumbu menempel merata; aduk cepat dan terus agar tidak lengket\nBumbui: tuang kecap manis dan (opsional) kecap asin; taburkan garam dan merica; aduk sampai warna merata dan nasi terasa wangi\nFinishing: masukkan irisan daun bawang; aduk 15–20 detik saja agar tetap segar\nKoreksi rasa: cicipi; jika kurang gurih tambah sedikit garam, jika kurang manis tambah kecap; jika kurang pedas tambah rawit ulek\nSajikan panas dengan kerupuk dan acar untuk menyeimbangkan rasa",
                "image": "https://img.freepik.com/free-photo/sausage-fried-rice-with-tomatoes-carrots-shiitake-mushrooms-plate_1150-27185.jpg?t=st=1766075808~exp=1766079408~hmac=3d3bb6d85770b61063e07c1ecf5304562088b112465ce2188fe74a010445ba03&w=2000",
            },
            {
                "title": "Ayam Goreng Lengkuas",
                "description": "Ayam goreng berbumbu gurih dengan taburan serundeng lengkuas renyah dan wangi.",
                "ingredients": "1 ekor ayam (900–1100 gram), potong 8–12 bagian\n600 ml air\n2 batang serai, memarkan\n2 lembar daun salam\n3 lembar daun jeruk\n2 sendok teh garam (sesuaikan)\n1 sendok teh gula pasir (opsional)\nMinyak banyak untuk menggoreng\nBumbu halus: 8 butir bawang merah\n4 siung bawang putih\n3 ruas lengkuas, parut halus (ambil ampasnya untuk serundeng)\n2 ruas jahe\n2 sendok teh ketumbar sangrai\n1/2 sendok teh merica\n1 ruas kunyit (opsional untuk warna)\nSerundeng: 150 gram lengkuas parut (jika kurang dari bumbu, tambah)\nSerundeng: 2 sendok makan kelapa parut (opsional agar lebih ramai)\nSerundeng: sejumput garam",
                "steps": "Haluskan bumbu: blender/ulek bawang merah, bawang putih, jahe, kunyit, ketumbar, merica sampai halus; campurkan dengan lengkuas parut\nUngkep ayam: masukkan ayam ke panci, tuang air, masukkan serai, daun salam, daun jeruk, bumbu halus; aduk rata hingga ayam terendam bumbu\nMasak ungkep: nyalakan api sedang sampai mendidih, lalu kecilkan; masak 30–40 menit hingga ayam empuk dan bumbu meresap; sesekali balik ayam agar bumbu merata\nPisahkan ayam dan ampas bumbu: angkat ayam, tiriskan; saring ampas lengkuas dan bumbu yang tersisa dari panci (ini akan jadi serundeng)\nKeringkan ayam: diamkan ayam 10 menit agar permukaan tidak terlalu basah supaya tidak meletup saat digoreng\nGoreng ayam: panaskan minyak banyak api sedang; goreng ayam sampai kuning keemasan dan kulitnya kering; angkat dan tiriskan\nGoreng serundeng lengkuas: masukkan ampas bumbu/lengkuas ke minyak yang lebih kecil apinya; goreng sambil diaduk terus hingga kering, renyah, dan berwarna keemasan; hati-hati cepat gosong\nTiriskan serundeng: angkat serundeng, tiriskan di tisu; tambahkan sejumput garam jika perlu\nSajikan: taburkan serundeng di atas ayam goreng; cocok dengan sambal dan lalapan",
                "image": "https://pixabay.com/id/images/search/ayam%20goreng%20lengkuas/",
            },
            {
                "title": "Pecel Lele",
                "description": "Lele goreng garing disajikan dengan sambal pedas segar dan lalapan renyah.",
                "ingredients": "4 ekor lele ukuran sedang, bersihkan (buang isi perut, kerat-kerat bagian badan)\n1 buah jeruk nipis (untuk menghilangkan amis)\n1 sendok teh garam\n1/2 sendok teh ketumbar bubuk\nMinyak banyak untuk menggoreng\nSambal: 8 cabai rawit merah\nSambal: 3 cabai merah keriting\nSambal: 2 siung bawang putih\nSambal: 6 butir bawang merah\nSambal: 1 buah tomat merah ukuran sedang\nSambal: 1/2 sendok teh terasi bakar\nSambal: 1 sendok teh gula merah sisir\nSambal: garam secukupnya\nSambal: 1 sendok makan minyak (dari bekas goreng) untuk mengulek (opsional)\nLalapan: timun\nLalapan: kemangi\nLalapan: kol\nLalapan: selada (opsional)",
                "steps": "Marinasi lele: lumuri lele dengan jeruk nipis dan garam, diamkan 10 menit lalu bilas cepat dan tiriskan; ini membantu mengurangi bau tanah/amis\nBumbui lele: taburi ketumbar bubuk dan sedikit garam; gosok merata hingga masuk ke keratan; diamkan 10–15 menit\nPanaskan minyak: gunakan minyak cukup banyak agar lele terendam sebagian; panaskan sampai benar-benar panas (uji: masukkan ujung sumpit, muncul gelembung aktif)\nGoreng lele: goreng lele api sedang agar matang sampai tulang; balik sekali saja agar tidak hancur; goreng hingga kulit garing dan warna keemasan; tiriskan\nSiapkan sambal: goreng sebentar cabai, bawang, tomat (boleh setengah layu saja agar sambal segar); angkat\nUlek sambal: ulek cabai, bawang, terasi, tomat hingga tekstur sesuai selera (halus atau kasar); tambahkan garam dan gula merah; koreksi rasa—harus pedas, asin-gurih, ada manis tipis\nFinishing sambal: jika mau lebih wangi, tuang 1 sdm minyak panas bekas goreng lele ke sambal lalu aduk\nSajikan: tata lele, sambal, dan lalapan; nikmati selagi panas",
                "image": "https://asset.kompas.com/crops/vhkkKrYsJtPGU9jIpuht1703nLs=/0x0:1000x667/1200x800/data/photo/2021/03/21/60569b33a2b3d.jpeg",
            },
            {
                "title": "Nasi Uduk",
                "description": "Nasi gurih yang dimasak dengan santan dan rempah, cocok untuk sarapan dengan lauk sederhana.",
                "ingredients": "2 cup beras, cuci hingga air hampir bening lalu tiriskan 10 menit\n300 ml santan sedang\n250 ml air (sesuaikan dengan jenis beras)\n2 lembar daun salam\n2 batang serai, memarkan\n2 lembar daun pandan, simpulkan\n1 sendok teh garam\nPelengkap opsional: telur dadar iris\nPelengkap opsional: ayam goreng\nPelengkap opsional: sambal kacang\nPelengkap opsional: timun iris",
                "steps": "Cuci beras: cuci 3–4 kali sampai air cucian lebih jernih; tiriskan agar tak terlalu berair\nSiapkan cairan: campur santan, air, garam; aduk sampai garam larut dan santan homogen\nMasukkan rempah: masukkan daun salam, serai, dan daun pandan ke dalam panci rice cooker/panci biasa\nMasak di rice cooker: masukkan beras, tuang campuran santan; aduk perlahan rata; tekan tombol cook\nJika pakai panci: masak api sedang sambil diaduk perlahan sampai menyusut; kecilkan api, tutup rapat, masak 15 menit; matikan api dan diamkan 10 menit\nAduk dan kukus singkat: setelah matang, aduk nasi agar uap keluar merata; diamkan 5 menit agar tekstur set\nSajikan: angkat rempah daun, sajikan nasi uduk hangat dengan pelengkap sesuai selera",
                "image": "https://img.freepik.com/free-photo/traditional-nasi-lemak-meal-composition_23-2149056822.jpg?t=st=1766075922~exp=1766079522~hmac=9c23e66c7eb11ccb5bcacc0762cdd1beae7cfe01e58bca2e4eee40e94890a4ff&w=2000",
            },
            {
                "title": "Sayur Lodeh",
                "description": "Sayur bersantan dengan isian sayur beragam, gurih, hangat, dan cocok untuk lauk rumahan.",
                "ingredients": "400 ml santan sedang\n600 ml air\n2 lembar daun salam\n1 ruas lengkuas, memarkan\n2 batang serai, memarkan\n2 sendok makan minyak untuk menumis\n2 sendok teh garam (sesuaikan)\n1/2 sendok teh gula pasir (opsional)\nIsi sayur: 1 buah labu siam, kupas dan potong korek\nIsi sayur: 1 buah terong ungu, potong sedang\nIsi sayur: 100 gram kacang panjang, potong 3–4 cm\nIsi sayur: 150 gram kol, potong kasar\nIsi sayur: 1 buah jagung manis, potong 3–4 bagian (opsional)\nIsi sayur: 100 gram tempe, potong dadu (opsional)\nBumbu halus: 8 butir bawang merah\nBumbu halus: 3 siung bawang putih\nBumbu halus: 3 butir kemiri sangrai\nBumbu halus: 2 ruas kencur (opsional)\nBumbu halus: 1 ruas kunyit\nBumbu halus: 1/2 sendok teh ketumbar",
                "steps": "Siapkan sayur: cuci semua sayuran; potong seragam agar matang bersamaan; khusus labu siam bisa direndam air garam 5 menit lalu bilas untuk mengurangi getah\nHaluskan bumbu: ulek/blender bumbu halus hingga lembut\nTumis bumbu: panaskan minyak, tumis bumbu halus hingga harum dan matang; masukkan daun salam, serai, lengkuas; tumis sampai aromanya keluar\nMasak kuah: tuang air, didihkan 5 menit agar bumbu larut; bumbui garam dan sedikit gula; aduk rata\nMasukkan sayur bertahap: masukkan jagung dan labu siam lebih dulu (paling lama matangnya); masak 5–7 menit\nMasukkan kacang panjang dan terong: masak 4–5 menit sampai mulai empuk\nTuang santan: kecilkan api; tuang santan sambil diaduk perlahan agar tidak pecah\nMasukkan kol dan tempe: masukkan kol terakhir agar tetap renyah; masak 2–3 menit; koreksi rasa\nMatikan api: jangan memasak terlalu lama setelah santan masuk agar kuah tidak pecah dan sayur tidak lembek; diamkan 5 menit sebelum disajikan",
                "image": "https://assets.unileversolutions.com/recipes-v2/230915.jpg",
            },
            {
                "title": "Tempe Orek Kering",
                "description": "Tempe orek manis gurih pedas yang awet dan cocok jadi lauk stok.",
                "ingredients": "1 papan tempe (350–400 gram), potong korek kecil\nMinyak banyak untuk menggoreng tempe\n5 butir bawang merah, iris tipis\n3 siung bawang putih, iris tipis\n4 cabai merah keriting, iris serong\n2 lembar daun salam\n2 cm lengkuas, memarkan\n3 sendok makan kecap manis\n1 sendok makan gula merah sisir\n1/2 sendok teh garam (sesuaikan)\n1/4 sendok teh merica\n2 sendok makan air (agar bumbu menyatu)\n1 sendok teh air asam jawa (opsional untuk rasa segar)",
                "steps": "Potong tempe: potong korek kecil seragam agar matang merata; keringkan sebentar di tisu agar tidak meletup\nGoreng tempe: panaskan minyak api sedang; goreng tempe sampai kering keemasan (bukan sekadar matang); tiriskan benar-benar agar hasil akhir renyah dan tidak cepat melempem\nTumis bumbu: gunakan sedikit minyak, tumis bawang merah dan bawang putih hingga harum dan agak layu; masukkan daun salam, lengkuas, dan irisan cabai; tumis sampai bawang agak kecokelatan\nBuat saus: masukkan kecap manis, gula merah, garam, merica, dan 2 sdm air; aduk kecilkan api; masak sampai gula larut dan saus sedikit berbuih\nMasukkan tempe: masukkan tempe goreng; aduk cepat hingga semua tempe terlapisi saus merata\nKeringkan: masak api kecil sambil diaduk sampai bumbu mengering menempel; jika ingin lebih kering, lanjutkan 2–3 menit sampai tempe benar-benar “kering lengket”\nDinginkan: angkat dan dinginkan di wadah terbuka agar uap hilang; setelah dingin baru simpan dalam toples agar tetap renyah",
                "image": "https://assets.unileversolutions.com/v1/51228806.jpg",
            },
            {
                "title": "Mie Goreng Jawa",
                "description": "Mie goreng dengan bumbu ulek khas Jawa, manis gurih, harum bawang dan telur.",
                "ingredients": "200 gram mie telur, rebus 2–3 menit sampai kenyal lalu tiriskan\n2 sendok makan minyak\n2 butir telur\n100 gram ayam suwir atau irisan bakso (opsional)\n2 genggam kol iris\n1 batang daun bawang iris\n1 genggam sawi hijau (opsional)\nBumbu halus: 6 butir bawang merah\nBumbu halus: 3 siung bawang putih\nBumbu halus: 3 cabai rawit\nBumbu halus: 1/2 sendok teh merica\nBumbu halus: 1/2 sendok teh garam\nBumbu cair: 2 sendok makan kecap manis\nBumbu cair: 1 sendok makan kecap asin (opsional)\nBumbu cair: 1 sendok makan saus tiram (opsional)\nBumbu cair: 2 sendok makan air kaldu/air",
                "steps": "Siapkan mie: rebus mie sebentar sampai al dente, bilas cepat air dingin agar stop matang dan tidak lengket; tiriskan hingga kering\nTumis bumbu: panaskan minyak api sedang; masukkan bumbu halus, tumis sampai harum dan matang\nMasukkan telur: buat ruang di tengah wajan; masukkan telur, orak-arik hingga setengah matang lalu campur dengan bumbu\nMasukkan isian: masukkan ayam/bakso, tumis sampai panas merata\nMasukkan sayur: masukkan kol dan sawi; aduk 1–2 menit sampai layu tapi masih renyah\nMasukkan mie: masukkan mie; aduk cepat agar tidak putus\nBumbui: tuang kecap manis, kecap asin, saus tiram, dan air; aduk sampai bumbu merata dan mie menyerap; masak sampai tidak ada cairan berlebih\nFinishing: masukkan daun bawang; aduk sebentar; koreksi rasa (tambah kecap untuk manis, garam untuk gurih)\nSajikan panas dengan acar/kerupuk",
                "image": "https://asset.kompas.com/crops/j_TbujltYD08I6UY35zeQHBs7FU=/28x12:996x657/1200x800/data/photo/2022/07/12/62ccdc61ccd88.jpg",
            },
            {
                "title": "Opor Ayam",
                "description": "Opor ayam bersantan dengan aroma rempah lembut, cocok untuk hidangan keluarga.",
                "ingredients": "1 ekor ayam, potong 8–10 bagian\n800 ml santan sedang\n400 ml air\n2 batang serai, memarkan\n2 lembar daun salam\n3 lembar daun jeruk\n2 cm lengkuas, memarkan\n2 sendok makan minyak\nGaram 2 sendok teh (sesuaikan)\nGula 1 sendok teh (opsional)\nBumbu halus: 10 butir bawang merah\n4 siung bawang putih\n4 butir kemiri sangrai\n2 ruas kunyit\n1 ruas jahe\n1/2 sendok teh ketumbar\n1/2 sendok teh merica",
                "steps": "Tumis bumbu: panaskan minyak, tumis bumbu halus sampai harum dan matang; masukkan serai, daun salam, daun jeruk, lengkuas; tumis 1–2 menit\nMasukkan ayam: masukkan ayam, aduk sampai ayam terlapisi bumbu; masak 5–7 menit sampai ayam berubah warna dan bumbu menempel\nTuang air: tambahkan air, didihkan kecil 15–20 menit agar ayam mulai empuk dan kaldu keluar\nTuang santan: kecilkan api; tuang santan sambil diaduk perlahan agar tidak pecah\nBumbui: masukkan garam dan gula; masak 20–30 menit api kecil sampai ayam empuk dan kuah mengental lembut; aduk sesekali agar tidak gosong\nKoreksi: cicipi; opor enak jika gurihnya halus, aroma kemiri dan kunyit terasa, tidak terlalu asin\nSajikan: cocok dengan ketupat/lontong dan sambal",
                "image": "https://img.freepik.com/free-photo/green-curry-made-with-chicken-chili-basil-with-tomato-lime-kaffir-lime-leaves-garlic_1150-25724.jpg?t=st=1766076038~exp=1766079638~hmac=70d4c6c6c3c25e2891a2cf5942c66f45f6bf5e0d6eec31b684113e2da6f09e6c&w=2000",
            },
            {
                "title": "Rawon",
                "description": "Sup daging sapi berkuah hitam dari kluwek, gurih dalam, dengan aroma khas Jawa Timur.",
                "ingredients": "700 gram daging sapi sandung lamur atau brisket, potong 3–4 cm\n2 liter air\n2 batang serai, memarkan\n3 lembar daun jeruk\n2 lembar daun salam\n2 cm lengkuas, memarkan\nGaram 2 sendok teh (sesuaikan)\nGula 1/2 sendok teh (opsional)\nBumbu halus: 8 butir bawang merah\n4 siung bawang putih\n4 butir kemiri sangrai\n5 buah kluwek, ambil isinya, rendam air hangat lalu saring (pastikan tidak pahit)\n1 ruas kunyit (opsional)\n1/2 sendok teh ketumbar\n1/2 sendok teh merica\n1 sendok teh terasi bakar (opsional)\n2 sendok makan minyak untuk menumis\nPelengkap: tauge pendek seduh\nPelengkap: telur asin\nPelengkap: sambal\nPelengkap: bawang goreng\nPelengkap: jeruk nipis",
                "steps": "Rebus daging: masukkan daging dan air, didihkan; buang buih agar kuah bersih; masukkan serai, daun jeruk, daun salam, lengkuas; rebus api kecil 60–90 menit sampai daging empuk\nSiapkan kluwek: pastikan kluwek tidak pahit; larutkan isi kluwek dengan sedikit air hangat, aduk, lalu saring agar bebas pasir\nTumis bumbu: haluskan bawang, kemiri, ketumbar, merica, kunyit, terasi; tumis hingga harum dan matang; masukkan larutan kluwek; tumis lagi sampai warna hitam pekat dan aroma kluwek keluar\nSatukan: masukkan bumbu tumis ke panci kuah; aduk rata; masak 15–20 menit api kecil agar bumbu menyatu\nBumbui: masukkan garam dan sedikit gula; cicipi—rawon harus gurih “dalam”, bukan sekadar asin\nSajikan: tata nasi, siram rawon, beri tauge seduh, taburi bawang goreng; tambahkan telur asin dan sambal sesuai selera",
                "image": "https://asset.kompas.com/crops/Z4AMIzm1FWyV8dPZFPLx5EcztsU=/0x0:780x520/1200x800/data/photo/2024/03/08/65eac6e4198d8.jpg",
            },
            {
                "title": "Gulai Ikan",
                "description": "Gulai ikan bersantan dengan rempah kuat, kuah kuning kemerahan, dan rasa gurih pedas segar.",
                "ingredients": "700 gram ikan (tongkol/kakap/ikan patin), potong sesuai selera\n1 buah jeruk nipis (untuk lumur ikan)\n1 sendok teh garam untuk ikan\n700 ml santan sedang\n300 ml air\n2 batang serai, memarkan\n3 lembar daun jeruk\n2 lembar daun salam\n1 ruas lengkuas, memarkan\n1 buah asam kandis atau 1 sdm air asam jawa (opsional)\n2 sendok makan minyak\nGaram 2 sendok teh (sesuaikan)\nGula 1/2 sendok teh (opsional)\nBumbu halus: 10 butir bawang merah\n4 siung bawang putih\n6 cabai merah keriting\n2 ruas kunyit\n2 ruas jahe\n3 butir kemiri sangrai\n1 sendok teh ketumbar\nPelengkap: daun kemangi segenggam (opsional)",
                "steps": "Siapkan ikan: lumuri ikan dengan jeruk nipis dan sedikit garam, diamkan 10 menit lalu bilas cepat; tiriskan agar tidak amis\nTumis bumbu: panaskan minyak, tumis bumbu halus hingga harum dan matang; masukkan serai, daun jeruk, daun salam, lengkuas; tumis sampai wangi\nMasak kuah: tuang air, didihkan 5–7 menit agar bumbu larut; masukkan asam kandis/air asam untuk rasa segar\nTuang santan: kecilkan api; tuang santan sambil diaduk perlahan agar tidak pecah; didihkan kecil\nMasukkan ikan: masukkan potongan ikan dengan hati-hati; jangan sering diaduk agar ikan tidak hancur; cukup goyang panci atau sendokkan kuah ke atas ikan\nBumbui: masukkan garam dan sedikit gula; masak 10–15 menit sampai ikan matang dan kuah mengental; koreksi rasa\nFinishing: masukkan daun kemangi 30 detik terakhir agar aromanya segar\nSajikan: gulai ikan enak disantap hangat dengan nasi putih",
                "image": "https://www.dapurkobe.co.id/wp-content/uploads/gulai-ikan-pedas.jpg",
            },
            {
                "title": "Sambal Goreng Kentang Ati",
                "description": "Kentang dan ati ampela dimasak bumbu merah santan ringan, pedas manis gurih, cocok untuk lauk.",
                "ingredients": "400 gram kentang, kupas dan potong dadu 1,5 cm\n300 gram ati ampela ayam, rebus hingga matang lalu potong dadu\nMinyak untuk menggoreng kentang\n2 lembar daun salam\n2 cm lengkuas, memarkan\n1 batang serai, memarkan\n200 ml santan encer (opsional, bisa tanpa santan)\n150 ml air\nGaram 1,5 sendok teh (sesuaikan)\nGula merah 1 sendok makan sisir\nBumbu halus: 8 butir bawang merah\n3 siung bawang putih\n6 cabai merah keriting\n3 cabai rawit (opsional)\n2 butir kemiri sangrai\n1 ruas jahe\n1/2 sendok teh terasi bakar (opsional)",
                "steps": "Goreng kentang: cuci kentang potong, keringkan, goreng hingga setengah matang lalu angkat; goreng lagi sebentar hingga bagian luar agak kering; tiriskan agar tidak lembek saat dimasak bumbu\nSiapkan ati ampela: rebus ati ampela hingga matang dan tidak amis; potong dadu; jika suka, tumis sebentar agar lebih wangi\nTumis bumbu: panaskan sedikit minyak, tumis bumbu halus hingga harum dan matang; masukkan daun salam, lengkuas, serai; tumis 1–2 menit\nMasak bumbu: tuang air (dan santan jika pakai); masukkan gula merah dan garam; didihkan kecil sampai bumbu agak mengental dan tidak mentah\nMasukkan isian: masukkan ati ampela, masak 5 menit agar bumbu meresap; masukkan kentang goreng terakhir; aduk pelan sampai bumbu menyelimuti\nKoreksi: cicipi; harus pedas gurih dengan manis tipis; jika ingin lebih kering, masak sampai kuah menyusut\nIstirahatkan: diamkan 10 menit sebelum disajikan agar bumbu makin meresap",
                "image": "https://assets.unileversolutions.com/recipes-v3/258268-default.jpg",
            },
            {
                "title": "Perkedel Kentang",
                "description": "Perkedel kentang lembut di dalam, gurih, dan renyah tipis di luar.",
                "ingredients": "600 gram kentang, kupas dan potong besar\nMinyak untuk menggoreng kentang\n2 siung bawang putih, haluskan\n2 batang daun seledri, iris halus\n1/2 sendok teh merica\n1 sendok teh garam (sesuaikan)\n1/2 sendok teh kaldu bubuk (opsional)\n1 butir telur untuk campuran adonan (opsional)\n2 butir telur untuk pelapis\nMinyak untuk menggoreng perkedel",
                "steps": "Goreng kentang: goreng potongan kentang sampai matang (bukan direbus) agar perkedel tidak lembek; tiriskan minyaknya\nHaluskan kentang: saat masih hangat, haluskan kentang dengan ulekan/penekan kentang sampai halus; hindari blender agar tekstur tidak jadi pasta\nBumbui adonan: masukkan bawang putih halus, seledri, merica, garam, dan kaldu bubuk; aduk rata; jika adonan terlalu rapuh, masukkan 1 butir telur ke adonan agar lebih menyatu\nBentuk: ambil adonan, bentuk oval pipih; padatkan dengan tangan agar tidak pecah saat digoreng\nPelapis: kocok 2 butir telur; celupkan perkedel ke telur hingga terlapisi tipis merata\nGoreng: panaskan minyak api sedang; goreng perkedel sampai kuning keemasan; balik sekali dengan hati-hati; tiriskan\nSajikan: enak sebagai lauk soto/rawon atau nasi hangat",
                "image": "https://images.tokopedia.net/img/KRMmCm/2024/2/19/b0be084c-e37b-4f7f-8bf4-e91350bd4ff3.jpg",
            },
            {
            "title": "Udang Saus Padang",
            "description": "Udang saus Padang pedas manis gurih dengan saus kental, wangi bawang, dan sedikit rasa segar dari tomat.",
            "ingredients": "600 gram udang ukuran sedang-besar (pilih yang masih segar, cangkang mengilap)\n1 buah jeruk nipis (untuk mengurangi amis)\n1 sendok teh garam untuk marinasi udang\n1/2 sendok teh merica untuk marinasi udang\n2 sendok makan minyak goreng (untuk menumis)\n1 sendok makan mentega (opsional, bikin saus lebih wangi dan creamy)\n1 buah bawang bombay ukuran sedang, iris tipis memanjang\n3 siung bawang putih, cincang halus\n5 butir bawang merah, iris tipis\n2 buah cabai merah besar, iris serong (untuk warna)\n6 buah cabai merah keriting, haluskan atau cincang (sesuaikan pedas)\n6 buah cabai rawit merah, haluskan (opsional, jika mau lebih nendang)\n1 buah tomat merah ukuran sedang, parut atau cincang halus (biar saus lebih segar)\n2 sendok makan saus tomat\n1 sendok makan saus sambal\n1 sendok makan saus tiram\n1 sendok makan kecap manis\n1 sendok teh kecap asin (opsional, untuk kedalaman rasa)\n200 ml air\n1 sendok teh gula pasir (atau 1 sdm gula merah sisir untuk rasa lebih “bold”)\n1–1,5 sendok teh garam (sesuaikan karena saus sudah asin)\n1/2 sendok teh merica\n1/2 sendok teh paprika bubuk (opsional, biar lebih wangi)\n1 sendok teh air jeruk nipis tambahan (opsional untuk finishing)\nLarutan pengental: 1 sendok teh maizena + 2 sendok makan air (opsional, kalau mau saus lebih kental)\nTaburan: daun bawang iris atau seledri iris (opsional)",
            "steps": "Bersihkan udang dengan benar: buang kepala jika kamu tidak suka, atau biarkan untuk rasa lebih gurih; kupas kulit secukupnya (boleh sisakan ekor untuk tampilan); belah punggung udang tipis lalu tarik kotoran hitamnya sampai bersih\nCuci udang cepat saja: jangan direndam lama supaya teksturnya tidak lembek; tiriskan sampai udang tidak terlalu berair\nMarinasi udang: lumuri udang dengan garam, merica, dan perasan jeruk nipis; aduk rata dan diamkan 10 menit; setelah itu bilas cepat (opsional) lalu tiriskan—tujuannya mengurangi amis tapi tidak meninggalkan rasa terlalu asam\nSiapkan bumbu: iris bawang bombay, iris bawang merah, cincang bawang putih; haluskan cabai keriting + rawit (kalau mau pedasnya menyatu) atau cincang kalau mau tekstur\nPanaskan wajan: pakai api sedang-besar; tuang minyak lalu masukkan mentega (kalau pakai) hingga meleleh; mentega bikin aroma lebih “restaurant style”\nTumis aromatik: masukkan bawang merah dan bawang putih terlebih dulu; tumis sampai harum dan mulai layu, jangan sampai gosong karena nanti saus pahit\nMasukkan bawang bombay: tumis sampai bawang bombay agak transparan; ini bikin saus manis alami dan wangi\nMasukkan cabai: masukkan cabai halus/cincang dan cabai merah iris; tumis sampai cabai benar-benar matang (warna lebih gelap dan tidak langu) supaya saus tidak terasa mentah\nTambahkan tomat: masukkan tomat cincang/parut; masak sampai tomat hancur dan menyatu; tomat bikin rasa saus lebih segar dan tidak “flat”\nBuat saus dasar: masukkan saus tomat, saus sambal, saus tiram, kecap manis, dan kecap asin (jika pakai); aduk rata sampai meletup kecil dan aromanya keluar\nTuang air: masukkan 200 ml air, aduk rata dan didihkan kecil 2–3 menit supaya semua bumbu larut dan rasa mulai menyatu\nBumbui dan koreksi: masukkan gula, garam, merica, dan paprika bubuk (opsional); cicipi—targetnya pedas gurih dengan manis tipis; kalau terlalu asam (dari tomat), tambahkan sedikit gula; kalau terlalu manis, tambahkan sedikit garam/saus tiram\nMasukkan udang: masukkan udang saat saus sudah mendidih kecil; aduk cepat agar udang terlapisi saus merata\nMasak udang dengan waktu pas: masak 3–5 menit saja (tergantung ukuran); udang matang ditandai warna berubah pink-oranye dan tubuh udang melengkung; jangan terlalu lama karena udang jadi keras dan kering\nKentalin saus bila perlu: jika saus terlalu encer, tuang larutan maizena sedikit demi sedikit sambil diaduk; masak 1 menit sampai saus mengilap dan kental; jika sudah pas, skip langkah ini\nFinishing rasa: matikan api; kalau suka ada sensasi segar, tambahkan 1 sendok teh perasan jeruk nipis dan aduk cepat (jangan kebanyakan biar tidak pahit)\nSajikan: taburi daun bawang/seledri; sajikan panas dengan nasi putih hangat; sausnya cocok banget buat disiram ke nasi",
            "image": "https://asset.kompas.com/crops/H0zAOZMJqTfWikUTtodZeKjQRY4=/0x0:1280x853/1200x800/data/photo/2020/08/06/5f2bd87e831f3.jpg",
            },
            {
            "title": "Muhammad Yusuf",
            "description": "Resep spesial ala Muhammad Yusuf, menggambarkan karakter yang rapi, detail, dan penuh konsistensi layaknya seorang master frontend.",
            "ingredients": "1 unit laptop dengan performa stabil\n1 cangkir kopi hitam tanpa gula (untuk fokus maksimal)\n2 sendok makan konsistensi belajar setiap hari\n1 porsi besar rasa penasaran terhadap teknologi baru\n1 genggam kesabaran menghadapi bug CSS yang tidak masuk akal\n3 lembar referensi desain modern (Figma, Dribbble, atau Behance)\n1 paket Tailwind CSS lengkap dengan utility class\n1 sendok teh logika layout (flexbox dan grid)\nSedikit humor agar tidak stres\nWaktu luang secukupnya di malam hari",
            "steps": "Nyalakan laptop dan pastikan lingkungan kerja nyaman, mulai dari posisi duduk hingga pencahayaan ruangan agar fokus tidak mudah hilang\nSeduh kopi hitam dan letakkan di samping laptop sebagai teman debugging panjang yang mungkin terjadi\nBuka referensi desain di Figma atau platform inspirasi lain, lalu pahami struktur layout, hierarki warna, dan konsistensi tipografi\nMulai setup project frontend dengan rapi, pastikan struktur folder jelas agar tidak menyulitkan pengembangan jangka panjang\nTerapkan styling dasar menggunakan Tailwind CSS, mulai dari layout utama dengan flexbox atau grid agar fondasi tampilan kuat\nSesuaikan warna, spacing, dan typography secara detail, perhatikan margin dan padding sekecil apa pun karena ini menentukan kualitas UI\nUji tampilan di berbagai ukuran layar untuk memastikan desain tetap responsif dan tidak rusak di device berbeda\nHadapi bug styling dengan tenang, gunakan Inspect Element untuk melacak masalah tanpa panik\nLakukan iterasi desain berulang kali sampai tampilan terasa bersih, nyaman dilihat, dan konsisten\nAkhiri proses dengan rasa puas, sambil berkata bahwa ini bukan sekadar tampilan, tapi hasil dari proses belajar yang matang",
            "image": "https://media.licdn.com/dms/image/v2/D5635AQGbOz_YK1x8Ng/profile-framedphoto-shrink_400_400/profile-framedphoto-shrink_400_400/0/1738816858283?e=1766682000&v=beta&t=hG7JYKzLk_yDx68kJgwtCaWPOrerK0tUedW1J6AqvjA",
            },
        ]

        # Tambahkan semua resep di atas jika belum ada
        for data in recipes_data:
            existing = dbsession.query(Recipe).filter_by(title=data['title']).first()
            if not existing:
                new_recipe = Recipe(**data)
                dbsession.add(new_recipe)

if __name__ == '__main__':
    main()
