"""init

Revision ID: 904463a5ab7b
Revises: 
Create Date: 2025-05-18 13:43:48.555454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904463a5ab7b'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
