"""Create model

Revision ID: 32bd502e1e7c
Revises: 68b7f8fd3dc8
Create Date: 2025-05-12 20:31:23.577868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32bd502e1e7c'
down_revision = '68b7f8fd3dc8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
